# Generated by Django 6.0.1 on 2026-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.BigIntegerField(editable=False, help_text='Sotib olingan vaqtdagi narxi'),
        ),
    ]
