# Generated by Django 6.0.1 on 2026-02-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(verbose_name="Zakar borishi kk bo'lgan manzil"),
        ),
    ]
