# Generated by Django 6.0.1 on 2026-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_order_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Mijoz'), ('operator', 'Operator')], default='client', max_length=30),
        ),
    ]
